
define([ "dojo/_base/declare",
         "esri/layers/ArcGISDynamicMapServiceLayer",
         "esri/layers/ArcGISTiledMapServiceLayer",
         "Widgets/baseWidget/BaseWidget",
         "Widgets/util/ajaxUtil",
         "dojo/_base/lang",
         "dojo/on",
         "dojo/topic",
         "dojo/query",
         "dojo/dom-style",
         "dojo/dom-class",
         "dojo/dom-attr",
         "dojo/dom-construct", 
         "dojo/dom",
         "dojo/html",
         "dojo/dnd/Moveable",
         "dojo/text!./templates/Template.html"],
    function(declare,ArcGISDynamicMapServiceLayer,ArcGISTiledMapServiceLayer,BaseWidget,ajaxUtil,lang,on,topic,query, 
    		domStyle,domClass,domAttr,domConstruct, dom,html,Moveable,template) {
	   
        return declare([BaseWidget], {
            templateString : template,           
            constructor : function(args) {           	
                this.inherited(arguments);
                this.map=args.map;
            },
            
            postCreate : function() {
                this.inherited(arguments);
                this.init();
                this.bindEvent();
            },
            
            startup:function(){
                this.inherited(arguments);   	
            },
            
            destroy:function(){
                this.inherited(arguments);
            },
            
            init:function(){    
            	setTimeout(lang.hitch(this,function(){           		
            		  this.showDataTab();            		               	
                }),0);              
            },            
            showDataTab:function(){            	           	
                topic.subscribe('Datadate',lang.hitch(this,function(data){
                	$.ajax({type:"post",url:"Data",data: {mtitle:data},
                		success:function(msg){
                			var $table = $('#DataTable');             			                			
                            $table.bootstrapTable({
                            dataType: "json",    
                            method: 'post',
                            contentType: "application/x-www-form-urlencoded",
                            pagination: true, //分页
                            pageSize:10,
                            striped:true,     //隔行变色
                            width:800,
                            height:500, 
                            pageList: [10, 25, 50, 100],
                            singleSelect: false,
                            search: true, //显示搜索框
                            clickToSelect: true,               
                                  columns: [                            
                                          {
                                              title: '测站名',
                                              field: 'name',
                                              align: 'center',
                                              valign: 'middle',
                                          }, 
                                          {
                                              title: '温度',
                                              field: 'Tem',
                                              align: 'center'
                                          },
                                          {
                                              title: '降水',
                                              field: 'Rain',
                                              align: 'center'
                                          },
                                          {
                                              title: '气压',
                                              field: 'Pressure',
                                              align: 'center',
                                          },
                                          {
                                              title: '相对湿度',
                                              field: 'Humid',
                                              align: 'center',
                                          },
                                          {
                                              title: '风速',
                                              field: 'Wind',
                                              align: 'center',
                                          },
                                          {
                                              title: '风向',
                                              field: 'WindDirection',
                                              align: 'center',
                                          }, 
                                      ],
                             onLoadSuccess: function(){          	 
                            	 console.log("成功");
                             },
                             onLoadError:function(){
                            	 console.log("失败");
                             }
                              });                              
                            var data = [
{"La":"30.9786","Lon":"112.5883","Tem":"4.4","Tem_max":"5.5","Tem_min":"4.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"71","Wind":"0.9","name":"柴湖","max_Tem":"5.5","min_Tem":"4.4"},
{"La":"31.3228","Lon":"0","Tem":"1.3","Tem_max":"2","Tem_min":"1.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"东川","max_Tem":"2","min_Tem":"1.2"},
{"La":"30.9283","Lon":"113.0003","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"中南山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.1169","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"南海","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.0336","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"卸甲坪","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9686","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"万家乡","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.0853","Lon":"0","Tem":"4.7","Tem_max":"5.6","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"三堰淌村","max_Tem":"5.6","min_Tem":"4.7"},
{"La":"30.2919","Lon":"0","Tem":"7.9","Tem_max":"8","Tem_min":"7.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"127","Wind":"0.7","name":"埠河","max_Tem":"8","min_Tem":"7.7"},
{"La":"29.7519","Lon":"0","Tem":"8.3","Tem_max":"9.7","Tem_min":"8.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.2","name":"藕池","max_Tem":"9.7","min_Tem":"8.3"},
{"La":"29.8767","Lon":"0","Tem":"7","Tem_max":"7.4","Tem_min":"7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"30","Wind":"0.3","name":"卷桥水库","max_Tem":"7.4","min_Tem":"7"},
{"La":"30.0667","Lon":"0","Tem":"7.8","Tem_max":"8","Tem_min":"7.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"周老嘴","max_Tem":"8","min_Tem":"7.5"},
{"La":"29.7167","Lon":"113.0333","Tem":"8.6","Tem_max":"9.5","Tem_min":"8.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"朱河","max_Tem":"9.5","min_Tem":"8.6"},
{"La":"29.9833","Lon":"113","Tem":"8.9","Tem_max":"9","Tem_min":"8.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"福田","max_Tem":"9","min_Tem":"8.9"},
{"La":"29.82","Lon":"113.0989","Tem":"8.2","Tem_max":"8.5","Tem_min":"8.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"汴河","max_Tem":"8.5","min_Tem":"8.2"},
{"La":"29.9325","Lon":"112.6222","Tem":"7.5","Tem_max":"7.5","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"程集","max_Tem":"7.5","min_Tem":"7.2"},
{"La":"29.8097","Lon":"112.89","Tem":"10","Tem_max":"10.2","Tem_min":"9.8","Humid":"72","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"长江村","max_Tem":"10.2","min_Tem":"9.8"},
{"La":"29.6061","Lon":"0","Tem":"8.8","Tem_max":"10.5","Tem_min":"8.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"螺山","max_Tem":"10.5","min_Tem":"8.8"},
{"La":"29.5092","Lon":"0","Tem":"7.8","Tem_max":"8.1","Tem_min":"7.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"乌林","max_Tem":"8.1","min_Tem":"7.5"},
{"La":"30.1333","Lon":"113.5561","Tem":"7.2","Tem_max":"7.3","Tem_min":"7.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"峰口","max_Tem":"7.3","min_Tem":"7.1"},
{"La":"29.8667","Lon":"113.4783","Tem":"8.8","Tem_max":"9.3","Tem_min":"8.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"22","Wind":"0.9","name":"滨湖","max_Tem":"9.3","min_Tem":"8.8"},
{"La":"30.3347","Lon":"0","Tem":"6.9","Tem_max":"7.3","Tem_min":"6.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"长大东区","max_Tem":"7.3","min_Tem":"6.8"},
{"La":"30.3664","Lon":"0","Tem":"7.2","Tem_max":"8.2","Tem_min":"7.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"郢城","max_Tem":"8.2","min_Tem":"7.1"},
{"La":"30.4681","Lon":"0","Tem":"5.5","Tem_max":"5.9","Tem_min":"5.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"菱角湖","max_Tem":"5.9","min_Tem":"5.4"},
{"La":"30.2703","Lon":"0","Tem":"8.5","Tem_max":"8.9","Tem_min":"8.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"岑河","max_Tem":"8.9","min_Tem":"8.4"},
{"La":"30.3333","Lon":"0","Tem":"7.9","Tem_max":"8.5","Tem_min":"7.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"观音挡","max_Tem":"8.5","min_Tem":"7.9"},
{"La":"30.1833","Lon":"0","Tem":"6.3","Tem_max":"6.3","Tem_min":"5.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"熊河","max_Tem":"6.3","min_Tem":"5.9"},
{"La":"30.3333","Lon":"0","Tem":"7.7","Tem_max":"9","Tem_min":"7.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"荆州老南门","max_Tem":"9","min_Tem":"7.6"},
{"La":"30.4142","Lon":"0","Tem":"6.9","Tem_max":"7.5","Tem_min":"6.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"91","Wind":"0.7","name":"宜汉高速太湖港","max_Tem":"7.5","min_Tem":"6.9"},
{"La":"31.53","Lon":"114.3589","Tem":"-0.1","Tem_max":"2","Tem_min":"-0.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"53","Wind":"0.2","name":"彭店","max_Tem":"2","min_Tem":"-0.3"},
{"La":"31.3736","Lon":"114.3764","Tem":"1.5","Tem_max":"2.3","Tem_min":"1.3","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"静风","Wind":"0","name":"刘集","max_Tem":"2.3","min_Tem":"1.3"},
{"La":"31.4042","Lon":"0","Tem":"1","Tem_max":"1.5","Tem_min":"0.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"329","Wind":"0.8","name":"夏店","max_Tem":"1.5","min_Tem":"0.7"},
{"La":"31.4042","Lon":"0","Tem":"3.7","Tem_max":"5.6","Tem_min":"3.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"153","Wind":"3.5","name":"黄站","max_Tem":"5.6","min_Tem":"3.7"},
{"La":"31.4661","Lon":"114.3389","Tem":"1.2","Tem_max":"1.8","Tem_min":"1.2","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"0","Wind":"0","name":"余河","max_Tem":"1.8","min_Tem":"1.2"},
{"La":"31.4928","Lon":"114.0847","Tem":"1.5","Tem_max":"1.6","Tem_min":"1.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"40","Wind":"1.5","name":"赵谷冲","max_Tem":"1.6","min_Tem":"1.2"},
{"La":"31.2675","Lon":"0","Tem":"5.2","Tem_max":"5.6","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.1","name":"陈店","max_Tem":"5.6","min_Tem":"5.2"},
{"La":"31.0297","Lon":"113.4494","Tem":"4","Tem_max":"4.7","Tem_min":"4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"田店","max_Tem":"4.7","min_Tem":"4"},
{"La":"30.7725","Lon":"0","Tem":"5.3","Tem_max":"5.7","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"100","Wind":"0.5","name":"天鹅","max_Tem":"5.7","min_Tem":"5.1"},
{"La":"31.0156","Lon":"113.5603","Tem":"2","Tem_max":"2.9","Tem_min":"1.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"322","Wind":"1","name":"盛滩","max_Tem":"2.9","min_Tem":"1.9"},
{"La":"29.6653","Lon":"0","Tem":"7.2","Tem_max":"8.1","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"130","Wind":"0.4","name":"汈汊湖","max_Tem":"8.1","min_Tem":"7.2"},
{"La":"31.3925","Lon":"0","Tem":"3.9","Tem_max":"4.3","Tem_min":"3.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"53","Wind":"0.8","name":"王店","max_Tem":"4.3","min_Tem":"3.7"},
{"La":"31.1639","Lon":"0","Tem":"2.4","Tem_max":"3.1","Tem_min":"2.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"周巷","max_Tem":"3.1","min_Tem":"2.3"},
{"La":"31.1378","Lon":"0","Tem":"3.6","Tem_max":"5.8","Tem_min":"3.6","Humid":"缺测","Rain":"0.1","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"白沙","max_Tem":"5.8","min_Tem":"3.6"},
{"La":"31.0933","Lon":"0","Tem":"6.1","Tem_max":"6.6","Tem_min":"6.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"95","Wind":"1.5","name":"义堂","max_Tem":"6.6","min_Tem":"6.1"},
{"La":"31.1206","Lon":"0","Tem":"5.7","Tem_max":"6.3","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"101","Wind":"0.3","name":"曾店","max_Tem":"6.3","min_Tem":"5.7"},
{"La":"30.9825","Lon":"0","Tem":"5.9","Tem_max":"6.6","Tem_min":"5.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"105","Wind":"1.4","name":"伍洛","max_Tem":"6.6","min_Tem":"5.9"},
{"La":"30.9461","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"隔蒲潭","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"31.0931","Lon":"0","Tem":"6.2","Tem_max":"6.4","Tem_min":"5.8","Humid":"67","Rain":"0","Pressure":"1020.1","WindDirection":"静风","Wind":"0","name":"肖港","max_Tem":"6.4","min_Tem":"5.8"},
{"La":"30.7981","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"东山头","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.7994","Lon":"0","Tem":"6.8","Tem_max":"7.2","Tem_min":"6.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"朱湖","max_Tem":"7.2","min_Tem":"6.8"},
{"La":"30.7278","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"拖市镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.6733","Lon":"0","Tem":"5.4","Tem_max":"6.2","Tem_min":"5.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"渔薪镇","max_Tem":"6.2","min_Tem":"5.4"},
{"La":"30.5769","Lon":"0","Tem":"4.6","Tem_max":"5.8","Tem_min":"4.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"张港镇","max_Tem":"5.8","min_Tem":"4.4"},
{"La":"30.7578","Lon":"0","Tem":"4.2","Tem_max":"4.4","Tem_min":"3.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"348","Wind":"1.2","name":"佛子山镇","max_Tem":"4.4","min_Tem":"3.8"},
{"La":"30.6122","Lon":"0","Tem":"6.3","Tem_max":"6.9","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"汪场镇","max_Tem":"6.9","min_Tem":"6.3"},
{"La":"30.8558","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"皂市镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.6569","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"净潭镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.5956","Lon":"0","Tem":"5","Tem_max":"5.6","Tem_min":"5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.1","name":"马湾镇","max_Tem":"5.6","min_Tem":"5"},
{"La":"30.6667","Lon":"0","Tem":"6.3","Tem_max":"7","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.1","name":"多宝","max_Tem":"7","min_Tem":"6.3"},
{"La":"30.4517","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"麻洋镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.9197","Lon":"0","Tem":"5.7","Tem_max":"6.2","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"石河镇","max_Tem":"6.2","min_Tem":"5.7"},
{"La":"30.5","Lon":"0","Tem":"5","Tem_max":"5.7","Tem_min":"4.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"沉湖","max_Tem":"5.7","min_Tem":"4.8"},
{"La":"30.6667","Lon":"0","Tem":"3.8","Tem_max":"4.3","Tem_min":"3.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"115","Wind":"0.3","name":"卢市","max_Tem":"4.3","min_Tem":"3.8"},
{"La":"30.5497","Lon":"112.6533","Tem":"5.3","Tem_max":"5.7","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.1","name":"高石碑镇","max_Tem":"5.7","min_Tem":"5.1"},
{"La":"30.5153","Lon":"112.7642","Tem":"4.3","Tem_max":"5.1","Tem_min":"4.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"100","Wind":"0","name":"广华镇","max_Tem":"5.1","min_Tem":"4.1"},
{"La":"30.375","Lon":"112.6408","Tem":"6.6","Tem_max":"7","Tem_min":"6.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"浩口镇","max_Tem":"7","min_Tem":"6.5"},
{"La":"30.3044","Lon":"112.7731","Tem":"4.6","Tem_max":"5.9","Tem_min":"4.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"26","Wind":"1","name":"熊口镇","max_Tem":"5.9","min_Tem":"4.5"},
{"La":"30.1892","Lon":"0","Tem":"5.9","Tem_max":"6","Tem_min":"5.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"134","Wind":"0.7","name":"张金镇","max_Tem":"6","min_Tem":"5.6"},
{"La":"30.5111","Lon":"112.7681","Tem":"7.1","Tem_max":"7.1","Tem_min":"6.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"后湖农场","max_Tem":"7.1","min_Tem":"6.9"},
{"La":"30.2828","Lon":"0","Tem":"4.7","Tem_max":"5.4","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"总口农场","max_Tem":"5.4","min_Tem":"4.7"},
{"La":"30.8056","Lon":"0","Tem":"5.3","Tem_max":"6","Tem_min":"5.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"周矶农场","max_Tem":"6","min_Tem":"5.3"},
{"La":"30.3","Lon":"112.6667","Tem":"6.9","Tem_max":"7","Tem_min":"6.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"43","Wind":"0.6","name":"熊口农场","max_Tem":"7","min_Tem":"6.5"},
{"La":"30.4172","Lon":"0","Tem":"4.6","Tem_max":"5","Tem_min":"4.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"32","Wind":"0.6","name":"市农科所","max_Tem":"5","min_Tem":"4.4"},
{"La":"30.3","Lon":"0","Tem":"5.4","Tem_max":"6.3","Tem_min":"5.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"郑场","max_Tem":"6.3","min_Tem":"5.4"},
{"La":"30.4172","Lon":"0","Tem":"6.5","Tem_max":"7.1","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"毛嘴","max_Tem":"7.1","min_Tem":"6.3"},
{"La":"30.3775","Lon":"113.2017","Tem":"5.1","Tem_max":"6.4","Tem_min":"5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"三伏潭","max_Tem":"6.4","min_Tem":"5"},
{"La":"30.3456","Lon":"113.3364","Tem":"5.8","Tem_max":"6.2","Tem_min":"5.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"周帮","max_Tem":"6.2","min_Tem":"5.8"},
{"La":"30.1422","Lon":"0","Tem":"7.7","Tem_max":"7.9","Tem_min":"7.5","Humid":"0","Rain":"0","Pressure":"1023","WindDirection":"142","Wind":"0.2","name":"杨林尾","max_Tem":"7.9","min_Tem":"7.5"},
{"La":"30.3422","Lon":"0","Tem":"6.9","Tem_max":"7.2","Tem_min":"6.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"剅河","max_Tem":"7.2","min_Tem":"6.9"},
{"La":"30.1833","Lon":"0","Tem":"6.8","Tem_max":"7.3","Tem_min":"6.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"沔城","max_Tem":"7.3","min_Tem":"6.8"},
{"La":"30.38","Lon":"0","Tem":"7","Tem_max":"8.5","Tem_min":"7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"151","Wind":"0.3","name":"胡场","max_Tem":"8.5","min_Tem":"7"},
{"La":"30.2","Lon":"113.7011","Tem":"8.2","Tem_max":"8.9","Tem_min":"7.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"203","Wind":"1.2","name":"彭场","max_Tem":"8.9","min_Tem":"7.7"},
{"La":"30.3375","Lon":"113.4606","Tem":"5","Tem_max":"5.6","Tem_min":"4.7","Humid":"92","Rain":"0","Pressure":"1023.1","WindDirection":"108","Wind":"0.4","name":"城区","max_Tem":"5.6","min_Tem":"4.7"},
{"Tem":"","Tem_max":"","Tem_min":"","Humid":"","Rain":"","Pressure":"","WindDirection":"","Wind":"","name":"","max_Tem":"","min_Tem":""},
{"La":"30.37","Lon":"113.43","Tem":"6.3","Tem_max":"6.8","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"张公","max_Tem":"6.8","min_Tem":"6.3"},
{"La":"29.965","Lon":"114.2992","Tem":"8.5","Tem_max":"8.8","Tem_min":"8.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"李家井水库","max_Tem":"8.8","min_Tem":"8.5"},
{"La":"29.9056","Lon":"114.5572","Tem":"5.8","Tem_max":"8","Tem_min":"5.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"9","Wind":"1","name":"苍梧岭","max_Tem":"8","min_Tem":"5.8"},
{"La":"30.1711","Lon":"114.0833","Tem":"6.8","Tem_max":"7.3","Tem_min":"6.8","Humid":"79","Rain":"0","Pressure":"1023.5","WindDirection":"静风","Wind":"0","name":"三乐闸","max_Tem":"7.3","min_Tem":"6.8"},
{"La":"29.9281","Lon":"113.8419","Tem":"6.7","Tem_max":"7.4","Tem_min":"6.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.1","name":"铜山村","max_Tem":"7.4","min_Tem":"6.6"},
{"La":"29.8922","Lon":"113.7081","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"赵李桥","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.5703","Lon":"113.7142","Tem":"7.2","Tem_max":"7.7","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"官塘","max_Tem":"7.7","min_Tem":"7.2"},
{"La":"29.7761","Lon":"114.085","Tem":"5.8","Tem_max":"6.2","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.2","name":"柳山湖","max_Tem":"6.2","min_Tem":"5.7"},
{"La":"29.8606","Lon":"113.6592","Tem":"7.3","Tem_max":"7.8","Tem_min":"7.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"张家坝","max_Tem":"7.8","min_Tem":"7.3"},
{"La":"29.8136","Lon":"113.9497","Tem":"8.2","Tem_max":"9.8","Tem_min":"8.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"340","Wind":"1.1","name":"老河泵站","max_Tem":"9.8","min_Tem":"8.2"},
{"La":"29.8225","Lon":"113.7036","Tem":"7.2","Tem_max":"7.7","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"54","Wind":"0.7","name":"沙坪","max_Tem":"7.7","min_Tem":"7.2"},
{"La":"29.3775","Lon":"113.8714","Tem":"8.6","Tem_max":"8.9","Tem_min":"8.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"肖岭","max_Tem":"8.9","min_Tem":"8.6"},
{"La":"29.3272","Lon":"113.8375","Tem":"8.9","Tem_max":"10","Tem_min":"8.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"大湖山","max_Tem":"10","min_Tem":"8.9"},
{"La":"29.2292","Lon":"114.1553","Tem":"6.9","Tem_max":"6.9","Tem_min":"6.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"192","Wind":"3.3","name":"路口","max_Tem":"6.9","min_Tem":"6.6"},
{"La":"29.5703","Lon":"114.2081","Tem":"6.5","Tem_max":"8.2","Tem_min":"6.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"102","Wind":"1.1","name":"塘口","max_Tem":"8.2","min_Tem":"6.2"},
{"La":"29.4283","Lon":"114.2606","Tem":"6.7","Tem_max":"8.3","Tem_min":"6.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"68","Wind":"0.9","name":"东源村","max_Tem":"8.3","min_Tem":"6.7"},
{"La":"29.5222","Lon":"112.8828","Tem":"4.7","Tem_max":"5.7","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"309","Wind":"0","name":"白螺","max_Tem":"5.7","min_Tem":"4.7"},
{"La":"0","Lon":"0","Tem":"6","Tem_max":"6.8","Tem_min":"5.9","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"322","Wind":"1.6","name":"麦市","max_Tem":"6.8","min_Tem":"5.9"},
{"La":"0","Lon":"113.9583","Tem":"9.5","Tem_max":"11.1","Tem_min":"9.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"关刀桥","max_Tem":"11.1","min_Tem":"9.5"},
{"La":"29.2181","Lon":"113.9039","Tem":"9.2","Tem_max":"10.3","Tem_min":"9.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"阔田","max_Tem":"10.3","min_Tem":"9.2"},
{"La":"0","Lon":"113.8344","Tem":"8.5","Tem_max":"9.9","Tem_min":"8.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"石南桥","max_Tem":"9.9","min_Tem":"8.5"},
{"La":"0","Lon":"113.7117","Tem":"7.8","Tem_max":"8.9","Tem_min":"7.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"神龙坪水库","max_Tem":"8.9","min_Tem":"7.8"},
{"La":"29.165","Lon":"113.7856","Tem":"9.1","Tem_max":"9.6","Tem_min":"8.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"54","Wind":"2","name":"东冲水库","max_Tem":"9.6","min_Tem":"8.7"},
{"La":"0","Lon":"113.6831","Tem":"9.7","Tem_max":"10.2","Tem_min":"9.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"327","Wind":"2.9","name":"云溪水库","max_Tem":"10.2","min_Tem":"9.7"},
{"La":"0","Lon":"113.8994","Tem":"9.6","Tem_max":"10.3","Tem_min":"9.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.2","name":"盘石","max_Tem":"10.3","min_Tem":"9.5"},
{"La":"0","Lon":"113.9294","Tem":"8.9","Tem_max":"9.8","Tem_min":"8.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"下畈村","max_Tem":"9.8","min_Tem":"8.6"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"方仕村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"治全村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.1264","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"程风村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.1883","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"大畈","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"114.6644","Tem":"8","Tem_max":"9.5","Tem_min":"8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"17","Wind":"0.5","name":"闯王","max_Tem":"9.5","min_Tem":"8"},
{"La":"0","Lon":"114.6206","Tem":"7.3","Tem_max":"8.1","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"黄沙","max_Tem":"8.1","min_Tem":"7.2"},
{"La":"29.7406","Lon":"114.6817","Tem":"5.3","Tem_max":"6.7","Tem_min":"5.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"杨芳","max_Tem":"6.7","min_Tem":"5.3"},
{"La":"29.4847","Lon":"114.3675","Tem":"5.8","Tem_max":"7.2","Tem_min":"5.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"燕厦","max_Tem":"7.2","min_Tem":"5.8"},
{"La":"29.5661","Lon":"114.8625","Tem":"8.3","Tem_max":"9.2","Tem_min":"8.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"九宫山","max_Tem":"9.2","min_Tem":"8.3"},
{"La":"0","Lon":"114.6681","Tem":"2.4","Tem_max":"3.3","Tem_min":"2.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"204","Wind":"1.7","name":"大路","max_Tem":"3.3","min_Tem":"2.3"},
{"La":"0","Lon":"114.4317","Tem":"6.6","Tem_max":"8.1","Tem_min":"6.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"望江岭","max_Tem":"8.1","min_Tem":"6.6"},
{"La":"0","Lon":"114.4925","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"沙店","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"114.8131","Tem":"8","Tem_max":"8.3","Tem_min":"8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"41","Wind":"1","name":"慈口","max_Tem":"8.3","min_Tem":"8"},
{"La":"29.6897","Lon":"0","Tem":"7.2","Tem_max":"8.6","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"8","Wind":"1","name":"梅田","max_Tem":"8.6","min_Tem":"7.2"},
{"La":"29.8092","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"西庄","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.7008","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"甘港","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.5481","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"青山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"洞口罗","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"沙堤","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"6.6","Tem_max":"8.1","Tem_min":"6.6","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"0","Wind":"0","name":"富有","max_Tem":"8.1","min_Tem":"6.6"},
{"La":"0","Lon":"0","Tem":"6.9","Tem_max":"8.2","Tem_min":"6.9","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"0","Wind":"0","name":"下陆","max_Tem":"8.2","min_Tem":"6.9"},
{"La":"0","Lon":"114.9481","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"铁山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"114.88","Tem":"6.3","Tem_max":"6.5","Tem_min":"6.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"119","Wind":"0.9","name":"西塞山","max_Tem":"6.5","min_Tem":"6.1"},
{"La":"0","Lon":"115.1025","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"堤防管理局","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.0931","Tem":"7.5","Tem_max":"7.9","Tem_min":"7.5","Humid":"88","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"铁矿","max_Tem":"7.9","min_Tem":"7.5"},
{"La":"0","Lon":"114.9119","Tem":"9.5","Tem_max":"9.5","Tem_min":"8.7","Humid":"38","Rain":"0","Pressure":"1004.8","WindDirection":"静风","Wind":"0","name":"棋盘洲","max_Tem":"9.5","min_Tem":"8.7"},
{"La":"0","Lon":"115.285","Tem":"-7.4","Tem_max":"-6.8","Tem_min":"-7.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"东方山","max_Tem":"-6.8","min_Tem":"-7.6"},
{"La":"30.2","Lon":"0","Tem":"8.2","Tem_max":"8.2","Tem_min":"7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"298","Wind":"1.1","name":"军分区","max_Tem":"8.2","min_Tem":"7"},
{"La":"30.24","Lon":"0","Tem":"4.7","Tem_max":"5.3","Tem_min":"4.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"殷祖镇","max_Tem":"5.3","min_Tem":"4.6"},
{"La":"0","Lon":"114.8756","Tem":"6.1","Tem_max":"6.8","Tem_min":"6.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"大箕铺镇","max_Tem":"6.8","min_Tem":"6.1"},
{"La":"30.0178","Lon":"115.0458","Tem":"5.5","Tem_max":"6.4","Tem_min":"5.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"144","Wind":"0.9","name":"保安镇","max_Tem":"6.4","min_Tem":"5.5"},
{"La":"30.1744","Lon":"114.7406","Tem":"6.8","Tem_max":"7.1","Tem_min":"6.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"157","Wind":"2.3","name":"刘仁八镇","max_Tem":"7.1","min_Tem":"6.7"},
{"La":"29.9464","Lon":"114.8475","Tem":"5.9","Tem_max":"6.8","Tem_min":"5.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"264","Wind":"1.1","name":"黄岗村","max_Tem":"6.8","min_Tem":"5.8"},
{"La":"30.3033","Lon":"114.7897","Tem":"7.1","Tem_max":"7.6","Tem_min":"7.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"还地桥镇","max_Tem":"7.6","min_Tem":"7.1"},
{"La":"30.2","Lon":"114.86","Tem":"4.5","Tem_max":"5.4","Tem_min":"4.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"177","Wind":"0.6","name":"港湖","max_Tem":"5.4","min_Tem":"4.5"},
{"La":"30.1331","Lon":"114.9706","Tem":"6.7","Tem_max":"7.2","Tem_min":"6.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"金山店铁矿","max_Tem":"7.2","min_Tem":"6.4"},
{"La":"30.8339","Lon":"114.4894","Tem":"7.2","Tem_max":"7.4","Tem_min":"6.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"324","Wind":"0.5","name":"灵乡","max_Tem":"7.4","min_Tem":"6.9"},
{"La":"30.0117","Lon":"114.7325","Tem":"5.5","Tem_max":"6.1","Tem_min":"5.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"岩山","max_Tem":"6.1","min_Tem":"5.5"},
{"La":"0","Lon":"114.8456","Tem":"5.5","Tem_max":"6.4","Tem_min":"5.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"172","Wind":"0.4","name":"董家口","max_Tem":"6.4","min_Tem":"5.5"},
{"La":"0","Lon":"114.9128","Tem":"6.3","Tem_max":"6.7","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"49","Wind":"0.9","name":"石家皖","max_Tem":"6.7","min_Tem":"6.3"},
{"La":"0","Lon":"115.0044","Tem":"5.5","Tem_max":"5.9","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"236","Wind":"1.8","name":"红峰水库","max_Tem":"5.9","min_Tem":"5.2"},
{"La":"0","Lon":"114.7256","Tem":"6.1","Tem_max":"6.4","Tem_min":"6.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"249","Wind":"0.7","name":"保安湖","max_Tem":"6.4","min_Tem":"6.1"},
{"La":"0","Lon":"114.6825","Tem":"6.8","Tem_max":"7.3","Tem_min":"6.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"167","Wind":"1.2","name":"均畈村","max_Tem":"7.3","min_Tem":"6.8"},
{"La":"30.1","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"后畈村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"曹铺村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"西畈村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9817","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"屏峰村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9547","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"土库村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.2533","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"下畈村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.2497","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"磨山村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.2633","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"黄泥村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.0133","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"徐家铺村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.1556","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"民爱村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.1417","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"桃花村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.1067","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"龙角山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9903","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"胡庚村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.0056","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"焦和村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.0514","Lon":"0","Tem":"4.9","Tem_max":"5.9","Tem_min":"4.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"51","Wind":"0.9","name":"","max_Tem":"5.9","min_Tem":"4.9"},
{"La":"30.1333","Lon":"0","Tem":"5.9","Tem_max":"7.1","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"36","Wind":"0.6","name":"富池镇","max_Tem":"7.1","min_Tem":"5.7"},
{"La":"0","Lon":"115.4358","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"王英镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.7961","Lon":"114.8264","Tem":"7.4","Tem_max":"8.2","Tem_min":"7.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"洋港镇","max_Tem":"8.2","min_Tem":"7.4"},
{"La":"29.5781","Lon":"115.1381","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"排市镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.7219","Lon":"115.055","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"枫林镇","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.7561","Lon":"115.4042","Tem":"6.5","Tem_max":"7.5","Tem_min":"6.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"浮屠镇","max_Tem":"7.5","min_Tem":"6.5"},
{"La":"29.8558","Lon":"115.0703","Tem":"5.7","Tem_max":"6.8","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"木港镇","max_Tem":"6.8","min_Tem":"5.7"},
{"La":"29.7233","Lon":"115.2467","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"王曙","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9456","Lon":"115.3908","Tem":"6.2","Tem_max":"7.8","Tem_min":"6.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"193","Wind":"1.8","name":"军垦","max_Tem":"7.8","min_Tem":"6.2"},
{"La":"29.8106","Lon":"115.0672","Tem":"5.9","Tem_max":"7","Tem_min":"5.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"白沙镇","max_Tem":"7","min_Tem":"5.9"},
{"La":"29.9464","Lon":"115.0506","Tem":"7.6","Tem_max":"8.4","Tem_min":"7.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"网湖","max_Tem":"8.4","min_Tem":"7.6"},
{"La":"29.9347","Lon":"115.2575","Tem":"7.3","Tem_max":"8.2","Tem_min":"7.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"202","Wind":"1.2","name":"吉山","max_Tem":"8.2","min_Tem":"7.3"},
{"La":"29.6992","Lon":"115.1689","Tem":"6.3","Tem_max":"7.5","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"鸡笼山","max_Tem":"7.5","min_Tem":"6.3"},
{"La":"29.8267","Lon":"115.4131","Tem":"6.6","Tem_max":"7.6","Tem_min":"6.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"太平村","max_Tem":"7.6","min_Tem":"6.6"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"韦源口镇镇府","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"新港村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"王崇村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"泉口村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.5817","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"星潭村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.7169","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"水源村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.7253","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"新街村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.8433","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"平湖林","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9897","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"石青村","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"29.9442","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"汀祖","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"114.9364","Tem":"5.5","Tem_max":"6.1","Tem_min":"5.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"241","Wind":"1.4","name":"燕矶","max_Tem":"6.1","min_Tem":"5.4"},
{"La":"0","Lon":"114.9239","Tem":"5.1","Tem_max":"6","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"265","Wind":"0","name":"杨叶","max_Tem":"6","min_Tem":"5.1"},
{"La":"0","Lon":"115.0664","Tem":"6.8","Tem_max":"7.3","Tem_min":"6.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"120","Wind":"1.2","name":"杜山","max_Tem":"7.3","min_Tem":"6.8"},
{"La":"0","Lon":"114.7881","Tem":"6.2","Tem_max":"6.9","Tem_min":"6.2","Humid":"74","Rain":"0","Pressure":"1024.3","WindDirection":"静风","Wind":"0","name":"程潮铁矿","max_Tem":"6.9","min_Tem":"6.2"},
{"La":"0","Lon":"114.8986","Tem":"9.5","Tem_max":"9.6","Tem_min":"9.2","Humid":"9","Rain":"0","Pressure":"1020.5","WindDirection":"149","Wind":"1.3","name":"庙岭","max_Tem":"9.6","min_Tem":"9.2"},
{"La":"0","Lon":"114.6253","Tem":"4.5","Tem_max":"5.2","Tem_min":"4.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"蒲团","max_Tem":"5.2","min_Tem":"4.4"},
{"La":"0","Lon":"114.7328","Tem":"5.3","Tem_max":"5.8","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"244","Wind":"0.6","name":"段店","max_Tem":"5.8","min_Tem":"5.2"},
{"La":"30.5397","Lon":"114.7692","Tem":"6.1","Tem_max":"6.7","Tem_min":"6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"85","Wind":"1.2","name":"临江","max_Tem":"6.7","min_Tem":"6"},
{"La":"0","Lon":"0","Tem":"5.9","Tem_max":"6","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"90","Wind":"1.3","name":"葛店","max_Tem":"6","min_Tem":"5.1"},
{"La":"30.5347","Lon":"114.6281","Tem":"5.8","Tem_max":"6.3","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.2","name":"太和","max_Tem":"6.3","min_Tem":"5.7"},
{"La":"30.1153","Lon":"114.68","Tem":"8.6","Tem_max":"8.9","Tem_min":"8.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"103","Wind":"1","name":"涂家垴","max_Tem":"8.9","min_Tem":"8.2"},
{"La":"30.1536","Lon":"114.5172","Tem":"5.2","Tem_max":"6.2","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"342","Wind":"0.5","name":"沼山","max_Tem":"6.2","min_Tem":"5.2"},
{"La":"30.0808","Lon":"114.5514","Tem":"5.6","Tem_max":"6.9","Tem_min":"5.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"143","Wind":"0.7","name":"梁子湖","max_Tem":"6.9","min_Tem":"5.6"},
{"La":"30.1833","Lon":"114.5728","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"东沟","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.2856","Lon":"114.6594","Tem":"7.6","Tem_max":"7.8","Tem_min":"7.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"114","Wind":"1.5","name":"狮子口水库","max_Tem":"7.8","min_Tem":"7.4"},
{"La":"30.0811","Lon":"114.7042","Tem":"6.6","Tem_max":"7.3","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"96","Wind":"1.2","name":"觅儿寺","max_Tem":"7.3","min_Tem":"6.3"},
{"La":"31.0378","Lon":"114.5356","Tem":"4.5","Tem_max":"5.1","Tem_min":"4.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"太平桥","max_Tem":"5.1","min_Tem":"4.4"},
{"La":"0","Lon":"114.6406","Tem":"3.3","Tem_max":"4.1","Tem_min":"3.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"永佳河","max_Tem":"4.1","min_Tem":"3.3"},
{"La":"0","Lon":"114.7069","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"陡山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"31.0558","Lon":"0","Tem":"1.8","Tem_max":"3.1","Tem_min":"1.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"38","Wind":"0.3","name":"戴长塘","max_Tem":"3.1","min_Tem":"1.8"},
{"La":"30.9886","Lon":"0","Tem":"2.6","Tem_max":"3.5","Tem_min":"2.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"344","Wind":"0.5","name":"依河墩","max_Tem":"3.5","min_Tem":"2.6"},
{"La":"31.0078","Lon":"0","Tem":"3.3","Tem_max":"4","Tem_min":"3.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"265","Wind":"0","name":"三河口","max_Tem":"4","min_Tem":"3.2"},
{"La":"0","Lon":"115.2333","Tem":"3.5","Tem_max":"4.8","Tem_min":"3.4","Humid":"78","Rain":"0","Pressure":"1011.7","WindDirection":"静风","Wind":"0","name":"熊家铺","max_Tem":"4.8","min_Tem":"3.4"},
{"La":"0","Lon":"115.2364","Tem":"2.9","Tem_max":"4.2","Tem_min":"2.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"顺河集","max_Tem":"4.2","min_Tem":"2.9"},
{"La":"0","Lon":"114.8364","Tem":"3","Tem_max":"4","Tem_min":"2.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"百果","max_Tem":"4","min_Tem":"2.9"},
{"La":"31.0336","Lon":"115.0167","Tem":"6.2","Tem_max":"6.9","Tem_min":"6.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"149","Wind":"0.9","name":"中驿","max_Tem":"6.9","min_Tem":"6.2"},
{"La":"0","Lon":"114.9144","Tem":"3.1","Tem_max":"4.5","Tem_min":"3.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"长岭岗","max_Tem":"4.5","min_Tem":"3.1"},
{"La":"0","Lon":"115.0442","Tem":"5.1","Tem_max":"5.6","Tem_min":"4.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"南湖","max_Tem":"5.6","min_Tem":"4.6"},
{"La":"0","Lon":"115.0069","Tem":"5.6","Tem_max":"6.3","Tem_min":"5.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.2","name":"明山","max_Tem":"6.3","min_Tem":"5.6"},
{"La":"0","Lon":"115.0133","Tem":"6.9","Tem_max":"8.1","Tem_min":"6.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"95","Wind":"3.2","name":"麻城老站","max_Tem":"8.1","min_Tem":"6.9"},
{"La":"31.17","Lon":"0","Tem":"5.6","Tem_max":"6.3","Tem_min":"5.6","Humid":"78","Rain":"0","Pressure":"1018.2","WindDirection":"58","Wind":"0.3","name":"匡河","max_Tem":"6.3","min_Tem":"5.6"},
{"La":"0","Lon":"115.5697","Tem":"4.5","Tem_max":"5.8","Tem_min":"4.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"天堂寨风景区","max_Tem":"5.8","min_Tem":"4.5"},
{"La":"0","Lon":"115.7031","Tem":"4.7","Tem_max":"5.9","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"三里畈","max_Tem":"5.9","min_Tem":"4.7"},
{"La":"0","Lon":"115.2669","Tem":"4.7","Tem_max":"5.8","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"大崎","max_Tem":"5.8","min_Tem":"4.7"},
{"La":"0","Lon":"115.1839","Tem":"4","Tem_max":"5.1","Tem_min":"3.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"13","Wind":"1.7","name":"严家畈","max_Tem":"5.1","min_Tem":"3.9"},
{"La":"30.9831","Lon":"0","Tem":"4.1","Tem_max":"5","Tem_min":"4.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"188","Wind":"0.5","name":"四级电站","max_Tem":"5","min_Tem":"4.1"},
{"La":"0","Lon":"0","Tem":"3.4","Tem_max":"5.3","Tem_min":"3.4","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"40","Wind":"0.1","name":"","max_Tem":"5.3","min_Tem":"3.4"},
{"La":"0","Lon":"0","Tem":"3.2","Tem_max":"5.2","Tem_min":"3","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"232","Wind":"1.2","name":"方家咀","max_Tem":"5.2","min_Tem":"3"},
{"La":"0","Lon":"0","Tem":"4","Tem_max":"5.9","Tem_min":"4","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"355","Wind":"0.5","name":"雷家店","max_Tem":"5.9","min_Tem":"4"},
{"La":"0","Lon":"115.6028","Tem":"5.8","Tem_max":"6.9","Tem_min":"5.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"石头咀","max_Tem":"6.9","min_Tem":"5.8"},
{"La":"0","Lon":"115.7431","Tem":"4.9","Tem_max":"6.5","Tem_min":"4.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"桃花冲","max_Tem":"6.5","min_Tem":"4.9"},
{"La":"0","Lon":"115.7661","Tem":"4.2","Tem_max":"6.2","Tem_min":"4.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"张家咀","max_Tem":"6.2","min_Tem":"4.2"},
{"La":"0","Lon":"116.0244","Tem":"3.6","Tem_max":"5.1","Tem_min":"3.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"303","Wind":"0.8","name":"乐园","max_Tem":"5.1","min_Tem":"3.6"},
{"La":"0","Lon":"115.8231","Tem":"2.9","Tem_max":"4.2","Tem_min":"2.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"195","Wind":"0.4","name":"四口冲","max_Tem":"4.2","min_Tem":"2.9"},
{"La":"0","Lon":"115.9397","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"203","Wind":"2.9","name":"双龙庙","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.6694","Tem":"5","Tem_max":"6.2","Tem_min":"4.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"吴家山","max_Tem":"6.2","min_Tem":"4.8"},
{"La":"0","Lon":"115.6861","Tem":"4.8","Tem_max":"6.2","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"315","Wind":"0.3","name":"吉子山","max_Tem":"6.2","min_Tem":"4.7"},
{"La":"31.0839","Lon":"115.7753","Tem":"4.4","Tem_max":"4.5","Tem_min":"3.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"214","Wind":"1.9","name":"胡家山","max_Tem":"4.5","min_Tem":"3.7"},
{"La":"0","Lon":"115.7483","Tem":"5.4","Tem_max":"5.9","Tem_min":"5.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"207","Wind":"1.9","name":"东庄畈","max_Tem":"5.9","min_Tem":"5.4"},
{"La":"31.0711","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"英太寨","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.8678","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"河口","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.9264","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"横山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"团陂","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"关口","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.4289","Lon":"115.1181","Tem":"5.1","Tem_max":"6","Tem_min":"5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"兰溪","max_Tem":"6","min_Tem":"5"},
{"La":"30.3456","Lon":"115.1531","Tem":"5.5","Tem_max":"6.6","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"白莲河","max_Tem":"6.6","min_Tem":"5.2"},
{"La":"0","Lon":"115.1431","Tem":"6.4","Tem_max":"7.5","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"竹瓦","max_Tem":"7.5","min_Tem":"6.3"},
{"La":"0","Lon":"115.2531","Tem":"6.4","Tem_max":"7.8","Tem_min":"6.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"洗马","max_Tem":"7.8","min_Tem":"6.4"},
{"La":"0","Lon":"115.4331","Tem":"4","Tem_max":"5.8","Tem_min":"4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"蔡河镇","max_Tem":"5.8","min_Tem":"4"},
{"La":"0","Lon":"115.4144","Tem":"3.9","Tem_max":"5.2","Tem_min":"3.9","Humid":"86","Rain":"0","Pressure":"1019.1","WindDirection":"静风","Wind":"0","name":"浠水","max_Tem":"5.2","min_Tem":"3.9"},
{"La":"0","Lon":"115.25","Tem":"6.2","Tem_max":"7","Tem_min":"6.2","Humid":"75","Rain":"0","Pressure":"1020.9","WindDirection":"0","Wind":"0","name":"叶家冲","max_Tem":"7","min_Tem":"6.2"},
{"La":"30.7733","Lon":"115.31","Tem":"2.9","Tem_max":"4.6","Tem_min":"2.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"高家坳","max_Tem":"4.6","min_Tem":"2.9"},
{"La":"30.6986","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"丰山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.6489","Lon":"0","Tem":"5.6","Tem_max":"6","Tem_min":"5.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"莲花","max_Tem":"6","min_Tem":"5.4"},
{"La":"30.5947","Lon":"0","Tem":"5.9","Tem_max":"6.5","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"54","Wind":"1","name":"黄河厂","max_Tem":"6.5","min_Tem":"5.7"},
{"La":"0","Lon":"115.5692","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"缺测","Wind":"缺测","name":"牛皮坳","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.0833","Lon":"115.3333","Tem":"5.8","Tem_max":"7","Tem_min":"5.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"横车","max_Tem":"7","min_Tem":"5.8"},
{"La":"30.3075","Lon":"115.3656","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"彭思","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.2833","Lon":"115.25","Tem":"4.7","Tem_max":"6.1","Tem_min":"4.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"48","Wind":"1.8","name":"向桥","max_Tem":"6.1","min_Tem":"4.7"},
{"La":"30.3","Lon":"115.8333","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"管窑","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"30.1669","Lon":"115.2847","Tem":"6.1","Tem_max":"7.7","Tem_min":"6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"田桥","max_Tem":"7.7","min_Tem":"6"},
{"La":"0","Lon":"115.75","Tem":"3.4","Tem_max":"5.2","Tem_min":"3.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"张榜","max_Tem":"5.2","min_Tem":"3.4"},
{"La":"0","Lon":"115.7933","Tem":"4.5","Tem_max":"6","Tem_min":"4.5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"352","Wind":"0.5","name":"赤东","max_Tem":"6","min_Tem":"4.5"},
{"La":"0","Lon":"115.455","Tem":"7.9","Tem_max":"8.2","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"65","Wind":"1.7","name":"狮子","max_Tem":"8.2","min_Tem":"7.2"},
{"La":"0","Lon":"115.6025","Tem":"5","Tem_max":"6.5","Tem_min":"5","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"青石","max_Tem":"6.5","min_Tem":"5"},
{"La":"0","Lon":"115.6719","Tem":"4.2","Tem_max":"5.3","Tem_min":"4.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"浏河曹庙","max_Tem":"5.3","min_Tem":"4.1"},
{"La":"0","Lon":"115.5786","Tem":"4.2","Tem_max":"5.6","Tem_min":"4.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"冯围","max_Tem":"5.6","min_Tem":"4.2"},
{"La":"30.2228","Lon":"115.4006","Tem":"4.6","Tem_max":"5.8","Tem_min":"4.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"14","Wind":"0.9","name":"土台","max_Tem":"5.8","min_Tem":"4.6"},
{"La":"30.0856","Lon":"115.3508","Tem":"5.1","Tem_max":"6.4","Tem_min":"5.1","Humid":"82","Rain":"0","Pressure":"1902/10/20 9:36:00","WindDirection":"静风","Wind":"0.2","name":"清水河","max_Tem":"6.4","min_Tem":"5.1"},
{"La":"0","Lon":"115.5003","Tem":"5.2","Tem_max":"5.9","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"桐梓","max_Tem":"5.9","min_Tem":"5.2"},
{"La":"0","Lon":"0","Tem":"3.8","Tem_max":"4.9","Tem_min":"3.8","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"149","Wind":"0.2","name":"孙冲","max_Tem":"4.9","min_Tem":"3.8"},
{"La":"0","Lon":"0","Tem":"3.7","Tem_max":"5.3","Tem_min":"3.7","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"0","Wind":"0","name":"檀林河东","max_Tem":"5.3","min_Tem":"3.7"},
{"La":"30.5928","Lon":"0","Tem":"3.8","Tem_max":"5.3","Tem_min":"3.8","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"335","Wind":"2.2","name":"挪步园","max_Tem":"5.3","min_Tem":"3.8"},
{"La":"0","Lon":"115.8042","Tem":"4.2","Tem_max":"4.8","Tem_min":"4","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"静风","Wind":"0","name":"小池","max_Tem":"4.8","min_Tem":"4"},
{"La":"0","Lon":"115.99","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"蔡山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.7869","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"孔垄","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.9033","Tem":"8","Tem_max":"8.4","Tem_min":"8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"163","Wind":"0.1","name":"濯港","max_Tem":"8.4","min_Tem":"8"},
{"La":"0","Lon":"115.8758","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"独山","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"116.0414","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"垅坪","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.9","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"下新","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.9836","Tem":"7.6","Tem_max":"8.2","Tem_min":"7.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"停前","max_Tem":"8.2","min_Tem":"7.6"},
{"La":"0","Lon":"115.9847","Tem":"5.9","Tem_max":"6.7","Tem_min":"5.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"2.2","name":"杉木","max_Tem":"6.7","min_Tem":"5.9"},
{"La":"0","Lon":"115.9786","Tem":"6.1","Tem_max":"7","Tem_min":"6.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"分路","max_Tem":"7","min_Tem":"6.1"},
{"La":"0","Lon":"115.9108","Tem":"7.7","Tem_max":"8.4","Tem_min":"7.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"18","Wind":"0.7","name":"沙湖","max_Tem":"8.4","min_Tem":"7.7"},
{"La":"29.9122","Lon":"115.9717","Tem":"7.6","Tem_max":"8.3","Tem_min":"7.6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"大河镇永安水库管理处","max_Tem":"8.3","min_Tem":"7.6"},
{"La":"0","Lon":"115.7767","Tem":"6.2","Tem_max":"7","Tem_min":"5.9","Humid":"77","Rain":"0","Pressure":"1020","WindDirection":"201","Wind":"0.3","name":"黄梅老站","max_Tem":"7","min_Tem":"5.9"},
{"La":"30.07","Lon":"115.93","Tem":"6.5","Tem_max":"7.3","Tem_min":"6.5","Humid":"72","Rain":"0","Pressure":"1024.5","WindDirection":"0","Wind":"0","name":"安山水库","max_Tem":"7.3","min_Tem":"6.5"},
{"La":"0","Lon":"115.8833","Tem":"5.2","Tem_max":"6.4","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"322","Wind":"1.3","name":"蔡田水库","max_Tem":"6.4","min_Tem":"5.1"},
{"La":"0","Lon":"0","Tem":"2.5","Tem_max":"4","Tem_min":"2.5","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"120","Wind":"0.1","name":"陶岭水库","max_Tem":"4","min_Tem":"2.5"},
{"La":"0","Lon":"0","Tem":"5.1","Tem_max":"6.2","Tem_min":"5","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"195","Wind":"1","name":"界子墩","max_Tem":"6.2","min_Tem":"5"},
{"La":"30.1175","Lon":"0","Tem":"5.1","Tem_max":"6.7","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"190","Wind":"0.9","name":"朱山站","max_Tem":"6.7","min_Tem":"5.1"},
{"La":"30.295","Lon":"0","Tem":"6.5","Tem_max":"6.7","Tem_min":"5.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"341","Wind":"0.1","name":"宋冲站","max_Tem":"6.7","min_Tem":"5.9"},
{"La":"30.1625","Lon":"0","Tem":"3.7","Tem_max":"5.1","Tem_min":"3.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"36","Wind":"0.1","name":"严畈站","max_Tem":"5.1","min_Tem":"3.7"},
{"La":"29.9989","Lon":"0","Tem":"7","Tem_max":"8","Tem_min":"7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"164","Wind":"0.2","name":"","max_Tem":"8","min_Tem":"7"},
{"La":"29.9975","Lon":"0","Tem":"5.5","Tem_max":"7.4","Tem_min":"5.4","Humid":"87","Rain":"0","Pressure":"缺测","WindDirection":"204","Wind":"0.3","name":"梅川水库","max_Tem":"7.4","min_Tem":"5.4"},
{"La":"0","Lon":"115.6228","Tem":"6.4","Tem_max":"7.2","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"69","Wind":"1","name":"大金水库","max_Tem":"7.2","min_Tem":"6.3"},
{"La":"0","Lon":"115.6181","Tem":"5.3","Tem_max":"6.5","Tem_min":"5.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.1","name":"南泉","max_Tem":"6.5","min_Tem":"5.3"},
{"La":"0","Lon":"115.5589","Tem":"5.3","Tem_max":"6.5","Tem_min":"5.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"121","Wind":"0.6","name":"大法寺","max_Tem":"6.5","min_Tem":"5.3"},
{"La":"0","Lon":"115.4836","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"花桥","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.7181","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"荆竹水库","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"115.6936","Tem":"6.2","Tem_max":"7.2","Tem_min":"6.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"287","Wind":"1.2","name":"盘搪","max_Tem":"7.2","min_Tem":"6.2"},
{"La":"0","Lon":"115.4167","Tem":"6.8","Tem_max":"8.1","Tem_min":"6.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"余川","max_Tem":"8.1","min_Tem":"6.8"},
{"La":"0","Lon":"115.6333","Tem":"6","Tem_max":"6.9","Tem_min":"6","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"农场","max_Tem":"6.9","min_Tem":"6"},
{"La":"0","Lon":"115.6514","Tem":"7.4","Tem_max":"7.9","Tem_min":"7.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"大闸","max_Tem":"7.9","min_Tem":"7.4"},
{"La":"29.8544","Lon":"115.6169","Tem":"7.4","Tem_max":"8","Tem_min":"7.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"53","Wind":"0.3","name":"四望","max_Tem":"8","min_Tem":"7.3"},
{"La":"30.0208","Lon":"115.5508","Tem":"5.2","Tem_max":"6.6","Tem_min":"5.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"大金","max_Tem":"6.6","min_Tem":"5.2"},
{"La":"29.9997","Lon":"115.1133","Tem":"6.3","Tem_max":"7","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"武穴城区消防","max_Tem":"7","min_Tem":"6.3"},
{"La":"29.8542","Lon":"115.5569","Tem":"7.1","Tem_max":"8","Tem_min":"7.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"砌石","max_Tem":"8","min_Tem":"7.1"},
{"La":"0","Lon":"115.6625","Tem":"5.1","Tem_max":"6.2","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"300","Wind":"0","name":"仙人坝水库","max_Tem":"6.2","min_Tem":"5.1"},
{"La":"0","Lon":"0","Tem":"5.6","Tem_max":"6.6","Tem_min":"5.6","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"357","Wind":"1.2","name":"西畈村","max_Tem":"6.6","min_Tem":"5.6"},
{"La":"0","Lon":"0","Tem":"6.2","Tem_max":"7.1","Tem_min":"6.2","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"147","Wind":"0.6","name":"从政村","max_Tem":"7.1","min_Tem":"6.2"},
{"La":"0","Lon":"0","Tem":"5.6","Tem_max":"6.8","Tem_min":"5.6","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"231","Wind":"0.2","name":"太白","max_Tem":"6.8","min_Tem":"5.6"},
{"La":"29.9764","Lon":"0","Tem":"6.6","Tem_max":"7.7","Tem_min":"6.6","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"123","Wind":"0.8","name":"贾庙","max_Tem":"7.7","min_Tem":"6.6"},
{"La":"0","Lon":"115.0992","Tem":"3.3","Tem_max":"4.4","Tem_min":"3.3","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"静风","Wind":"0.1","name":"王家坊","max_Tem":"4.4","min_Tem":"3.3"},
{"La":"0","Lon":"114.85","Tem":"6.4","Tem_max":"7","Tem_min":"6.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"141","Wind":"1.3","name":"上巴河","max_Tem":"7","min_Tem":"6.4"},
{"La":"0","Lon":"115.1333","Tem":"5.3","Tem_max":"6.5","Tem_min":"5.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"350","Wind":"0.9","name":"淋山河","max_Tem":"6.5","min_Tem":"5.3"},
{"La":"0","Lon":"114.8883","Tem":"7.1","Tem_max":"7.7","Tem_min":"7.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"总路咀","max_Tem":"7.7","min_Tem":"7.1"},
{"La":"0","Lon":"115.0739","Tem":"6.3","Tem_max":"7","Tem_min":"6.3","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"马曹庙","max_Tem":"7","min_Tem":"6.3"},
{"La":"0","Lon":"115.0472","Tem":"5.1","Tem_max":"6","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"但店镇","max_Tem":"6","min_Tem":"5.1"},
{"La":"0","Lon":"115.1781","Tem":"5.1","Tem_max":"6.1","Tem_min":"5.1","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"332","Wind":"0.8","name":"方高坪","max_Tem":"6.1","min_Tem":"5.1"},
{"La":"0","Lon":"114.9142","Tem":"5.7","Tem_max":"7.9","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0","name":"祥林奶牛基地","max_Tem":"7.9","min_Tem":"5.7"},
{"La":"0","Lon":"114.9561","Tem":"4.4","Tem_max":"5.9","Tem_min":"4.4","Humid":"76","Rain":"0","Pressure":"1018.8","WindDirection":"152","Wind":"0.7","name":"百丈岩","max_Tem":"5.9","min_Tem":"4.4"},
{"La":"30.7794","Lon":"115.0442","Tem":"4.8","Tem_max":"5.4","Tem_min":"4.8","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"0","Wind":"0","name":"熊家山六组","max_Tem":"5.4","min_Tem":"4.8"},
{"La":"30.8428","Lon":"0","Tem":"6.4","Tem_max":"7","Tem_min":"6.4","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"126","Wind":"1.5","name":"水晶坳","max_Tem":"7","min_Tem":"6.4"},
{"La":"30.8458","Lon":"0","Tem":"5.8","Tem_max":"6.7","Tem_min":"5.7","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"167","Wind":"2","name":"胡家山","max_Tem":"6.7","min_Tem":"5.7"},
{"La":"0","Lon":"0","Tem":"缺测","Tem_max":"缺测","Tem_min":"缺测","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"340","Wind":"0.5","name":"李家大湾","max_Tem":"缺测","min_Tem":"缺测"},
{"La":"0","Lon":"0","Tem":"8.8","Tem_max":"9","Tem_min":"8","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"89","Wind":"2.4","name":"","max_Tem":"9","min_Tem":"8"},
{"La":"0","Lon":"0","Tem":"4.5","Tem_max":"5","Tem_min":"4.5","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"326","Wind":"1","name":"茶场","max_Tem":"5","min_Tem":"4.5"},
{"La":"0","Lon":"0","Tem":"3.8","Tem_max":"4.4","Tem_min":"3.7","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"316","Wind":"0.8","name":"小琦山一组","max_Tem":"4.4","min_Tem":"3.7"},
{"La":"0","Lon":"0","Tem":"2.8","Tem_max":"3.7","Tem_min":"2.6","Humid":"缺测","Rain":"0","Pressure":"4637/11/25","WindDirection":"48","Wind":"0.2","name":"陈策楼","max_Tem":"3.7","min_Tem":"2.6"},
{"La":"0","Lon":"115.0219","Tem":"6.3","Tem_max":"6.5","Tem_min":"6.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"59","Wind":"2","name":"堵城","max_Tem":"6.5","min_Tem":"6.2"},
{"La":"0","Lon":"114.9011","Tem":"4.9","Tem_max":"6.3","Tem_min":"4.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"缺测","Wind":"缺测","name":"路口","max_Tem":"6.3","min_Tem":"4.9"},
{"La":"0","Lon":"114.9339","Tem":"7.2","Tem_max":"7.5","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"120","Wind":"0.5","name":"黄州","max_Tem":"7.5","min_Tem":"7.2"},
{"La":"0","Lon":"114.53","Tem":"8.1","Tem_max":"8.4","Tem_min":"7.9","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"95","Wind":"0.3","name":"南湖","max_Tem":"8.4","min_Tem":"7.9"},
{"La":"0","Lon":"114.9667","Tem":"7.2","Tem_max":"8.2","Tem_min":"7.2","Humid":"缺测","Rain":"0","Pressure":"缺测","WindDirection":"静风","Wind":"0.2","name":"","max_Tem":"8.2","min_Tem":"7.2"}]

                            $table.bootstrapTable('append',data);   
                		}}); 
                	
                }));
            },
            
            bindEvent:function(){
            	on(this.guanbi,"click",lang.hitch(this,function(){
            		this.destroy();
            	}));    
            },
        
        })
    }
);